// <auto-generated />
namespace LAB_3_onceMore.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class asddgender : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(asddgender));
        
        string IMigrationMetadata.Id
        {
            get { return "202405262125048_asdd-gender"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
