// <auto-generated />
namespace MVC_Vezbi_database.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class addedClientMovieRealationship : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addedClientMovieRealationship));
        
        string IMigrationMetadata.Id
        {
            get { return "202405021814260_addedClientMovieRealationship"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
